name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python for Demo
        uses: actions/setup-python@v4
      - name: Install depedencies
        run: pip install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Print branch
        run: echo "Nom de branche ${{ github.ref }}"
      - name: Print OS
        run: echo "OS ${{ runner.os }}"
